# Generated by Django 2.1.1 on 2020-11-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('activity_type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('timestamp', models.IntegerField()),
                ('heartrate', models.IntegerField()),
                ('distance', models.FloatField()),
                ('moving_time', models.IntegerField()),
                ('elevation', models.FloatField()),
                ('speed', models.FloatField()),
                ('suffer', models.IntegerField()),
            ],
        ),
    ]
