# Generated by Django 2.1.5 on 2020-11-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
    ]
