# Generated by Django 2.1.5 on 2020-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_strava_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
