# Generated by Django 2.1.5 on 2020-11-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20201127_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
