# Generated by Django 2.1.5 on 2020-11-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20201127_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
