# Generated by Django 2.1.5 on 2020-11-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20201127_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
