# Generated by Django 2.1.5 on 2020-11-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20201127_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
