# Generated by Django 2.1.5 on 2021-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20201127_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='elevation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='workout_type',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
