songs = ["The Pretender"
,"Psycho"
,"New Born"
,"Breaking The Girl"
,"La Solitudine"
,"Worn Down Piano"
,"Gaia"
,"Max"
,"Time To Give"
,"Bigger than us"
,"Iron Sky"
,"Seven Days In Sunny June"
,"Time won't wait"
,"Sweet Victory"
,"Killing In The Name"
,"Scenes From An Italian Restaurant"
,"Find The River"
,"Gotta Catch 'M All (Pokemon Theme Song)"
,"The Great Gig In The Sky"
,"Por una cabeza"
,"Shiver"
,"Diamonds"
,"R U Mine?"
,"Grounds For Divorce"
,"One Day Like This"
,"What You Know"
,"Sometimes It Snows In April"
,"How Soon Is Now"
,"All The Things She Said"
,"Another Love"
,"Take Me To Church"
,"Stolen Dance"
,"9 Crimes"
,"No One Knows"
,"Waterfall"]
songs_judith = ["Find The River"
,"Kiss From A Rose"
,"The Boxer"
,"Virtual Insanity"
,"Blackbird"
,"Lose Yourself"
,"Little Lies"
,"Sultans Of Swing"
,"Imagine"
,"Tears In Heaven"
,"Eternal Flame"
,"Hurt"
,"Piano Man"
,"Oceaan"
,"Here Comes The Sun"
,"Another One Bites The Dust"
,"Brown Eyed Girl"
,"Ruby"
,"50 Ways To Say Goodbye"
,"Have I Told You Lately"
,"Budapest"
,"Down Under"
,"Sweet Home Alabama"
,"Lola Montez"
,"Breakfast At Tiffany's"
,"Close To Me"
,"Chandelier"]